services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres_ztp_project2
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_ztp
    ports:
      - "8025:8025"
      - "1025:1025"

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy_ztp
    command: serve
    ports:
      - "8088:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus_ztp
    volumes:
      - ./.config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  adminer:
    image: adminer
    container_name: adminer_ztp
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
