CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    min_price NUMERIC(10, 2) NOT NULL,
    max_price NUMERIC(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    category_id INTEGER REFERENCES categories(id),
    price NUMERIC(10, 2) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0
);

INSERT INTO categories (name, min_price, max_price) VALUES
    ('Elektronika', 50.00, 15000.00),
    ('Odziez', 10.00, 2000.00),
    ('Spozywcze', 0.50, 500.00);

INSERT INTO products (name, category_id, price, quantity) VALUES
    ('Laptop', 1, 3499.99, 10),
    ('Smartfon', 1, 1299.00, 25),
    ('Sluchawki', 1, 249.99, 50),
    ('Kurtka', 2, 399.00, 30),
    ('Tshirt', 2, 59.99, 100),
    ('Chleb', 3, 4.50, 200),
    ('Maslo', 3, 8.99, 150);
