CREATE TABLE IF NOT EXISTS product_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    action VARCHAR NOT NULL,
    previous_state JSONB NOT NULL,
    current_state JSONB NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_product_history_product_id
    ON product_history(product_id);
