CREATE TABLE IF NOT EXISTS notifications (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR NOT NULL,
    channel VARCHAR NOT NULL,
    recipient VARCHAR NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    timezone VARCHAR NOT NULL,
    status VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    idempotency_key VARCHAR UNIQUE NOT NULL
);

INSERT INTO notifications (content, channel, recipient, scheduled_at, timezone, status, idempotency_key) VALUES ('Zamowienie zrealizowane', 'EMAIL', 'test@test.com', NOW() - INTERVAL '1 day', 'Europe/Warsaw', 'SENT', 'notif_1'), ('B��d wysy�ki', 'EMAIL', 'test@test.com', NOW() - INTERVAL '2 days', 'Europe/Warsaw', 'FAILED', 'notif_2'), ('Oczekiwanie...', 'PUSH', 'test@test.com', NOW() + INTERVAL '1 day', 'Europe/Warsaw', 'PENDING', 'notif_3');
