CREATE TABLE IF NOT EXISTS faculties (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS fields_of_study (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR UNIQUE NOT NULL,
    faculty_id INTEGER NOT NULL,
    min_ects INTEGER NOT NULL,
    max_ects INTEGER NOT NULL,
    CONSTRAINT fk_fields_of_study_faculty
        FOREIGN KEY (faculty_id)
        REFERENCES faculties(id)
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    lastname VARCHAR NOT NULL,
    student_code VARCHAR UNIQUE NOT NULL,
    email VARCHAR UNIQUE NOT NULL,
    field_of_study_id INTEGER NOT NULL,
    ects_points INTEGER NOT NULL,
    CONSTRAINT fk_students_field_of_study
        FOREIGN KEY (field_of_study_id)
        REFERENCES fields_of_study(id)
);

CREATE TABLE IF NOT EXISTS forbidden_email_phrases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase VARCHAR UNIQUE NOT NULL
);

INSERT INTO faculties (name)
VALUES
    ('Wydział Informatyki'),
    ('Wydział Matematyki'),
    ('Wydział Fizyki')
ON CONFLICT (name) DO NOTHING;

INSERT INTO fields_of_study (name, faculty_id, min_ects, max_ects)
VALUES
    ('Informatyka', 1, 30, 60),
    ('Matematyka Stosowana', 2, 25, 60),
    ('Fizyka Techniczna', 3, 20, 60)
ON CONFLICT (name) DO NOTHING;

INSERT INTO students (name, lastname, student_code, email, field_of_study_id, ects_points)
VALUES
    ('Jan', 'Kowalski', 'STU001', 'jan.kowalski@student.edu.pl', 1, 45),
    ('Anna', 'Nowak', 'STU002', 'anna.nowak@student.edu.pl', 2, 30),
    ('Piotr', 'Wiśniewski', 'STU003', 'piotr.wisniewski@student.edu.pl', 3, 25)
ON CONFLICT (student_code) DO NOTHING;

INSERT INTO forbidden_email_phrases (phrase)
VALUES
    ('test'),
    ('admin'),
    ('root'),
    ('spam')
ON CONFLICT (phrase) DO NOTHING;