CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    category_id INTEGER REFERENCES categories(id),
    price NUMERIC(10, 2) NOT NULL
);

INSERT INTO categories (name) VALUES
    ('Elektronika'),
    ('Odzież'),
    ('Artykuły spożywcze');

INSERT INTO products (name, category_id, price) VALUES
    ('Laptop', 1, 3499.99),
    ('Smartfon', 1, 1299.00),
    ('Słuchawki', 1, 249.99),
    ('Kurtka zimowa', 2, 399.00),
    ('T-shirt', 2, 59.99),
    ('Chleb pszenny', 3, 4.50),
    ('Masło', 3, 8.99);
