CREATE TABLE IF NOT EXISTS forbidden_product_names (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase VARCHAR UNIQUE NOT NULL
);

INSERT INTO forbidden_product_names (phrase)
VALUES
    ('test'),
    ('fake'),
    ('unknown')
ON CONFLICT (phrase) DO NOTHING;
